apiVersion: v1
metadata:
  creationTimestamp: null
  name: mysql-secret
kind: Secret
data:
  db-name: d29yZHByZXNzDQo=   # base64 for "wordpress"
  db-password: MTIzNDUNCg0K   # base64 for "12345"
  db-user:  bWV0YWJhc2UNCg==  # base64 for "metabase"  